<?php
require_once 'functions.php';

$data = parse_reading_data($_GET);
$stats = calculate_stats($data);

$exporting = isset($_GET['exporting']) && $_GET['exporting'] == 1;

// JS 数据准备
$js_today_data = json_encode($data['today_dist']);
$js_today_labels = json_encode(["0-2点", "2-4点", "4-6点", "6-8点", "8-10点", "10-12点", "12-14点", "14-16点", "16-18点", "18-20点", "20-22点", "22-24点"]);

$daily_values = array_values($data['daily_data']);
$daily_keys = array_keys($data['daily_data']);
$week_data = array_slice($daily_values, -7); 
$week_labels = array_map(function($d){ return $d."日"; }, array_slice($daily_keys, -7));
$js_week_data = json_encode($week_data);
$js_week_labels = json_encode($week_labels);

$comment_today = generate_comment('today', $data['today_dist'], ["0-2点", "2-4点", "4-6点", "6-8点", "8-10点", "10-12点", "12-14点", "14-16点", "16-18点", "18-20点", "20-22点", "22-24点"]);
$week_assoc = array_combine(array_slice($daily_keys, -7), $week_data);
$comment_week = generate_comment('week', $week_assoc);
$comment_month = "本月目标 {$data['goal']} 分钟/天，已达标 {$stats['goal_days']} 天。";
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>阅读报告 - <?php echo $data['year']; ?>/<?php echo $data['month']; ?></title>

    <link href="style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="https://www.tqhyg.net/wp-content/themes/Sakurairo/css/font-awesome-animation.min.css" rel="stylesheet">

    <style>
        :root { --primary-color: #0d6efd; --bg-color: #f4f7f9; }
        body { background: var(--bg-color); padding-bottom: 100px; font-family: system-ui, -apple-system, sans-serif; }
    </style>
</head>

<body <?php echo $exporting ? 'class="export-mode"' : ''; ?>>

<div class="container py-4" id="export-container">
    <div id="capture-area">
        <div class="d-flex justify-content-between align-items-end mb-4 px-2">
            <div>
                <h3 class="fw-bold mb-0 text-dark">阅读统计分析报告</h3>
                <span class="badge bg-primary-subtle text-primary mt-2 px-3 py-2 rounded-pill">
                    <i class="fa-regular fa-calendar-check me-1"></i> <?php echo $data['year']; ?>年<?php echo $data['month']; ?>月
                </span>
            </div>
            <div class="text-end d-none d-md-block">
                <small class="text-muted">Generated by Kindle Plugin</small>
            </div>
        </div>

        <div id="sec-overview" class="stat-card">
            <div class="row text-center g-3">
                <div class="col-6 col-md-3">
                    <div class="highlight-num text-primary"><?php echo $stats['today_total']; ?></div>
                    <div class="sub-label">今日时长(m)</div>
                </div>
                <div class="col-6 col-md-3">
                    <div class="highlight-num"><?php echo $stats['total_month']; ?></div>
                    <div class="sub-label">本月累计(m)</div>
                </div>
                <div class="col-6 col-md-3">
                    <div class="highlight-num text-success"><?php echo $stats['goal_days']; ?></div>
                    <div class="sub-label">达标天数</div>
                </div>
                <div class="col-6 col-md-3">
                    <div class="highlight-num text-warning"><?php echo $stats['streak']; ?></div>
                    <div class="sub-label">连续达标(天)</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div id="sec-today" class="stat-card">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h6 class="fw-bold m-0"><i class="fa-solid fa-chart-simple text-primary me-2"></i>今日时段分布</h6>
                        <button class="btn btn-sm btn-outline-light text-muted border-0" onclick="quickExport('sec-today', '今日分布')"><i class="fa-solid fa-camera"></i> 导出</button>
                    </div>
                    <div class="chart-container">
                        <canvas id="todayChart"></canvas>
                    </div>
                    <p class="small text-muted mt-3 mb-0 bg-light p-2 rounded">
                        <i class="fa-solid fa-quote-left me-1 opacity-50"></i> <?php echo strip_tags($comment_today); ?>
                    </p>
                </div>
            </div>

            <div class="col-md-6">
                <div id="sec-week" class="stat-card">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h6 class="fw-bold m-0"><i class="fa-solid fa-chart-line text-primary me-2"></i>近七天趋势</h6>
                        <button class="btn btn-sm btn-outline-light text-muted border-0" onclick="quickExport('sec-week', '周趋势')"><i class="fa-solid fa-camera"></i> 导出</button>
                    </div>
                    <div class="chart-container">
                        <canvas id="weekChart"></canvas>
                    </div>
                    <p class="small text-muted mt-3 mb-0 bg-light p-2 rounded">
                        <i class="fa-solid fa-quote-left me-1 opacity-50"></i> <?php echo strip_tags($comment_week); ?>
                    </p>
                </div>
            </div>
        </div>

        <div id="sec-month" class="stat-card">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h6 class="fw-bold m-0"><i class="fa-solid fa-calendar-days text-primary me-2"></i>全月阅读日历</h6>
                <button class="btn btn-sm btn-outline-light text-muted border-0" onclick="quickExport('sec-month', '月日历')"><i class="fa-solid fa-camera"></i> 导出</button>
            </div>
            
            <div class="calendar-scroll-area">
                <div class="calendar-grid-container">
                    <div class="calendar-grid mb-2">
                        <div class="calendar-day-header">SUN</div><div class="calendar-day-header">MON</div>
                        <div class="calendar-day-header">TUE</div><div class="calendar-day-header">WED</div>
                        <div class="calendar-day-header">THU</div><div class="calendar-day-header">FRI</div>
                        <div class="calendar-day-header">SAT</div>
                    </div>
                    <div class="calendar-grid">
                        <?php
                        $first_day_ts = mktime(0, 0, 0, $data['month'], 1, $data['year']);
                        $first_day_of_week = date('w', $first_day_ts);
                        $days_in_month = date('t', $first_day_ts);

                        for ($k = 0; $k < $first_day_of_week; $k++) echo "<div></div>";

                        for ($day = 1; $day <= $days_in_month; $day++) {
                            $min = $data['daily_data'][$day] ?? 0;
                            $style = $min >= $data['goal'] ? 'goal-reached' : ($min > 0 ? 'active' : '');
                            echo "<div class='day-cell {$style}'>";
                            echo "<span class='day-num'>{$day}</span>";
                            if($min > 0) echo "<span class='day-time'>{$min}m</span>";
                            echo "</div>";
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fab-container">
    <button class="btn btn-primary btn-fab shadow" onclick="exportFullReport()">
        <i class="fa-solid fa-download me-2"></i> 保存完整长图报告
    </button>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
<script>
    const urlParams = new URLSearchParams(window.location.search);
    const exportMode = urlParams.get('exporting') === '1';
    const isMobile = exportMode ? false : window.innerWidth < 768;

    // 坐标轴设置
    const pcConfig = {
        indexAxis: 'x',
        scales: {
            x: {
                ticks: { maxRotation: 60 },
                grid: { display: false }
            },
            y: {
                beginAtZero: true,
                ticks: {
                    callback: function(value) { return value + 'm'; }
                }
            }
        }
    };

    const mobileConfig = {
        indexAxis: 'y',
        scales: {
            x: {
                beginAtZero: true,
                ticks: {
                    callback: function(value) { return value + 'm'; }
                }
            },
            y: {
                reverse: false
            }
        }
    };

    // 根据设备类型合并配置
    const baseOptions = {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false } }
    };

    const finalOptions = isMobile 
        ? Object.assign({}, baseOptions, mobileConfig)
        : Object.assign({}, baseOptions, pcConfig);


    // 今日分布
    new Chart(document.getElementById('todayChart'), {
        type: 'bar', 
        data: {
            labels: <?php echo $js_today_labels; ?>,
            datasets: [{
                label: '分钟',
                data: <?php echo $js_today_data; ?>,
                backgroundColor: 'rgba(13, 110, 253, 0.7)',
                borderRadius: 6
            }]
        },
        options: finalOptions
    });


    // 本周分布
    new Chart(document.getElementById('weekChart'), {
        type: 'bar', 
        data: {
            labels: <?php echo $js_week_labels; ?>,
            datasets: [{
                label: '分钟',
                data: <?php echo $js_week_data; ?>,
                backgroundColor: 'rgba(13, 110, 253, 0.7)',
                borderRadius: 6
            }]
        },
        options: finalOptions 
    });

    // 导出函数
    async function sectionExport(element, filename) {
        // 临时增加 padding 防止截图边缘切断阴影
        const originalPadding = element.style.padding;

        const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                backgroundColor: "#d1ecfeff",
            });

        const link = document.createElement('a');
        link.href = canvas.toDataURL('image/png');
        link.download = filename + '.png';
        link.click();
    }

    async function fullExport(element, filename) {
        if (window.innerWidth < 768) {
            // 构建新URL，添加参数
            const currentUrl = window.location.href;
            const separator = currentUrl.includes('?') ? '&' : '?';
            const exportUrl = `${currentUrl}${separator}exporting=1`;
            
            // 打开新窗口
            const exportWindow = window.open(exportUrl, '_blank');
            
            // 等待新窗口加载完成后，监听导出事件
            if (exportWindow) {
                // 设置一个标记，防止重复导出
                window.exportInProgress = true;
                
                // 监听新窗口的消息（新窗口导出完成后会发送消息）
                window.addEventListener('message', function(event) {
                    if (event.data === 'export_complete') {
                        // 新窗口可以关闭了
                        try {
                            console.log('新窗口导出结束');
                            //exportWindow.close();
                        } catch (e) {
                            console.log('新窗口已关闭或无法关闭');
                        }
                        window.exportInProgress = false;
                    }
                });
                
                return; // 手机端直接返回，后续在新窗口处理
            }
        }
        const fab = document.querySelector('.fab-container');

        // 1. 锁定宽度并隐藏UI
        fab.style.visibility = 'hidden';

        try {
            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                backgroundColor: "#d1ecfeff",
                windowWidth: 1000 // 强制渲染器按此宽度解析
            });

            const link = document.createElement('a');
            link.href = canvas.toDataURL('image/png');
            link.download = filename + '.png';
            link.click();
        } catch (e) {
            console.log('生成失败');
        }
    }

    function quickExport(id, name) {
        sectionExport(document.getElementById(id), '阅读统计-' + name);
    }

    function exportFullReport() {
        // 原有逻辑
        fullExport(document.getElementById('capture-area'), '阅读报告全程回顾');
    }

    if (exportMode) {
        // 隐藏悬浮按钮
        document.querySelector('.fab-container').style.display = 'none';
            
        // 添加一个提示信息
        const notice = document.createElement('div');
        notice.id = 'export-notice';
        notice.innerHTML = '<div style="position: fixed; top: 10px; left: 10px; right: 10px; background: #ffc107; padding: 20px; border-radius: 5px; text-align: left; z-index: 10000;">正在生成截图，请稍候...</div>';
        document.body.appendChild(notice);

        // 延迟执行导出，确保页面完全渲染
        setTimeout(async () => {
            try {
                const canvas = await html2canvas(document.getElementById('capture-area'), {
                    scale: 2,
                    useCORS: true,
                    backgroundColor: "#daf0ffff",
                    windowWidth: 1200
                });

                const link = document.createElement('a');
                link.href = canvas.toDataURL('image/png');
                link.download = '阅读报告全程回顾.png';
                link.click();
                    
                // 移除提示
                document.getElementById('export-notice').remove();
                    
                // 通知父窗口导出完成
                if (window.opener) {
                    window.opener.postMessage('export_complete', '*');
                }
                    
            } catch (error) {
                console.error('导出失败:', error);
                document.getElementById('export-notice').innerHTML = 
                    '<div style="position: fixed; top: 10px; left: 10px; right: 10px; background: #dc3545; color: white; padding: 10px; border-radius: 5px; text-align: center; z-index: 10000;">导出失败，请重试</div>';
            }
        }, 1000);
    }
</script>

</body>
</html>